services:
  traefik:
    container_name: traefik
    image: traefik:v3.2.1
    command: --configFile=/etc/traefik/traefik.yaml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./acme.json:/acme.json
    networks:
      - traefik

networks:
  traefik:
    external: true